UBUNTU: SAUCE: dell_uart_backlight: size_t -> ssize_t
BugLink: https://bugs.launchpad.net/bugs/2083800

The prototype will be changed after v6.9-rc1, but we don't want to
introduce this commit, because it affects all drivers which uses serdev.
fed99212acae ("treewide, serdev: change receive_buf() return type to size_t")
Manually change the backlight driver prototype to ssize_t to fix the issue.

drivers/platform/x86/dell/dell-uart-backlight.c:265:24: error: initialization of 'ssize_t (*)(struct serdev_device *, const u8 *, size_t)' {aka 'long int (*)(struct serdev_device *, const unsigned char *, long unsigned int)'} from incompatible pointer type 'size_t (*)(struct serdev_device *, const u8 *, size_t)' {aka 'long unsigned int (*)(struct serdev_device *, const unsigned char *, long unsigned int)'} [-Werror=incompatible-pointer-types]
   265 |         .receive_buf = dell_uart_bl_receive,
       |                        ^~~~~~~~~~~~~~~~~~~~

Signed-off-by: Chia-Lin Kao (AceLan)<acelan.kao@canonical.com>
Acked-by: Paolo Pisati <paolo.pisati@canonical.com>
Acked-by: Mehmet Basaran <mehmet.basaran@canonical.com>
Signed-off-by: Stefan Bader <stefan.bader@canonical.com>